# fly.toml app configuration file generated for yannis-sefsaf-full-stack-open-pokedex on 2023-12-30T23:15:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yannis-sefsaf-full-stack-open-pokedex"
primary_region = "gdl"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
