app = "yannis-sefsaf-full-stack-open-pokedex"
primary_region = "gdl"

[deploy]
  release_command = "npm run build"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    grace_period = "1s"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
