name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install dependencies
          run: npm install
        - name: Lint
          run: npm run eslint
        - name: Build
          run: npm run build
        - name: Test
          run: npm run test
        - name: e2e tests
          uses: cypress-io/github-action@v5
          with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:8080
        - name: Intentional Error
          run: exit 1

  deploy:
    runs-on: ubuntu-20.04
    needs: build_and_test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install dependencies
          run: npm install
        - name: Lint
          run: npm run eslint
        - name: Build
          run: npm run build
        - name: Deploy app
          uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        - name: Check App Health
          run: |
            response=$(curl -o /dev/null -s -w "%{http_code}\n" https://yannis-sefsaf-full-stack-open-pokedex.fly.dev/health)
            if [ "$response" != "200" ]; then
            echo "Health check failed with status code: $response"
            exit 1
            fi
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # Discord notification on successful deployment
        - name: Discord notification on success
          if: success()
          uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
          with:
            args: 'Deployment successful! The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        
  tag_release:
    runs-on: ubuntu-20.04
    needs: deploy
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
        - uses: actions/checkout@v4
          
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.67.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
            DEFAULT_BUMP: patch   
         # Discord notification on successful tagging
        - name: Discord notification on tag
          if: success()
          uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
          with:
            args: 'New version tagged! The project {{ EVENT_PAYLOAD.repository.full_name }} has a new release.'
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  notify_failure:
    runs-on: ubuntu-20.04
    needs: build_and_test
    if: failure()
    steps:
        - uses: actions/checkout@v4
        # Discord notification on build failure
        - name: Discord notification on failure
          uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            COMMIT_SHA: ${{ github.sha }}
          with:
            args: 'Build failed! Commit SHA: {{ COMMIT_SHA }}. Please check the build logs.'